topics:
  reservation:
    request:  hotel-reservation-request
    response:  hotel-reservation-response

spring:
  datasource:
    url: jdbc:postgresql://localhost:8786/
    password: postgres
    username: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect