version: '3.8'

services:
  broker:
    image: rabbitmq:3-management
    container_name: rabbitmq-broker
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - internal

networks:
  internal: