version: '3.8'

services:
  broker:
    image: rabbitmq:3-management
    container_name: rabbitmq-broker
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - internal

  booking-db:
    image: postgres:13
    container_name: booking-db
    ports:
      - "8786:5432"
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=postgres"
    networks:
      - internal

  hotel-db:
    image: postgres:13
    container_name: hotel-db
    ports:
      - "8787:5432"
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=postgres"
    networks:
      - internal

networks:
  internal: